---
 - name: test
   hosts: build
   vars_files:
     - vars/creds.yml

   tasks:
     - name: login
       docker_login:
         username: AWS
         registry: "{{ ecr_id }}"
         password: "{{ ecr_password }}"