---
 - name: Prepare instances
   hosts: build, production
   remote_user: ubuntu
   become: yes
   become_user: root

   tasks:
     - name: install pip, docker
       apt:
         name: ['docker.io', 'python3', 'python3-pip']
         state: latest
         update_cache: yes
     - name: install boto, docker api
       pip:
         name: ['boto', 'boto3', 'botocore', 'docker']
     - name: Copy credentials from localhost
       copy:
         src: ~/.aws/credentials
         dest: ~/.aws/
         mode: 0644

# - name: Build webapp
#   hosts: build
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#
#   tasks:
#     - name: install maven
#       apt:
#         name: maven
#         state: present
#         update_cache: yes
#     - name: Clone repository
#       git:
#         repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
#         dest: /tmp/boxfuse-sample-java-war-hello/
#     - name: Package webapp
#       shell: cd /tmp/boxfuse-sample-java-war-hello/; mvn package
#     - name: Put artifact in bucket
#       aws_s3:
#         bucket: practicebacket.test1.com
#         object: /webapp/hello-1.0.war
#         src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
#         mode: put
#
# - name: Deploy app in prod
#   hosts: production
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#
#   tasks:
#     - name: install tomcat
#       apt:
#         name: tomcat9
#         state: present
#         update_cache: yes
##     - name: List bucket
##       aws_s3:
##         bucket: practicebacket.test1.com
##         mode: list
##     - name: Wait 15 seconds
##       pause:
##         seconds: 15
#     - name: Get artifact from bucket
#       aws_s3:
#         bucket: practicebacket.test1.com
#         object: /webapp/hello-1.0.war
#         dest: /var/lib/tomcat9/webapps/hello-1.0.war
#         mode: get
#     - name: Restart tomcat
#       ansible.builtin.service:
#         name: tomcat9
#         state: restarted
