---
 - name: Prepare instances
   hosts: build, production
   remote_user: ubuntu
   become: yes
   become_user: root

   tasks:
     - name: install pip, docker
       apt:
         name: ['docker.io', 'python3', 'python3-pip']
         state: latest
         update_cache: yes
     - name: install boto, docker api
       pip:
         name: ['boto', 'boto3', 'botocore', 'docker']
     - name: Copy credentials from localhost
       copy:
         src: ~/.aws/credentials
         dest: ~/.aws/
         mode: 0644