  GNU nano 4.8                                                                                 docker-compose.yml
version: '3.9'
services:
   build:
     build: build
     volumes:
       - type: volume
         source: app42
         target: /tmp/test1/target/

   db:
     image: mysql:5.7
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: app42
       MYSQL_USER: user
       MYSQL_PASSWORD: password
     ports:
       - 3306:3306

   web:
     depends_on:
       - db
     image: tomcat:latest
     volumes:
       - type: volume
         source: app42
         target: /usr/local/tomcat/webapps/
     links:
       - db
     ports:
       - '8080:8080'

volumes:
  app42: