---
# tasks file for docker-prepare
- name: Ensure packages is present
  apt: 
    name: ['python3-pip', 'docker.io']
    update_cache: yes
    state: present

- name: Ensure docker API is present
  pip:
    name: docker
    state: present
...
