---
 - name: provisioning EC2 instances
   hosts: localhost
   connection: local
   gather_facts: False

   vars:
     keypair: MyKey1
     instance_type: t2.micro
     image: ami-092cce4a19b438926
     wait: yes
     group: test
     count: 1
     region: eu-north-1
     security_group: my-sec-group-1

   tasks:

    - name: Create security group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for test Servers
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
            proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall
    - name: create keypair
      local_action:
        module: ec2_key
          name: {{ keypair }}
    - name: Lauch EC2 instance
      local_action: ec2
                    group={{ security_group }}
                    instance_type={{ instance_type }}
                    image={{ image }}
                    wait=true
                    region={{ region }}
                    keypair={{ keypair }}
                    count={{ count }}
      register: ec2
    - name: Add tagging to EC2 instance
    local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
    with_items: "{{ ec2.instance }}"
    args:
      tags:
        Name: BuildEc2Instance