---
- name: Prepare remote hosts for work with Docker
  hosts: build, production
  become: yes

  tasks:
  - name: Install pip
    apt:
      name: python3-pip
      update_cache: yes

  - name: Install docker
    apt:
      name: docker.io
      update_cache: yes

  - name: Install Docker API
    pip:
      name: docker

- name: Package artifact in Docker
  hosts: build
  become: yes

  tasks:
  - name: Copy container from localhost
    copy:
      src: /home/user/ansible-docker/docker-build/Dockerfile
      dest: /tmp/docker/
      mode: 0644

  - name: Build container
    docker_image:
      build:
        path: /tmp/docker/
      name: build

  - name: Start container
    docker_container:
      name: build
      image: build

  - name: Copy artifact from container
    shell: "mkdir /tmp/webapps; docker cp build:/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/webapps"

  - name: Fetch artifact from remote host
    fetch:
      src: /tmp/webapps/hello-1.0.war
      dest: /tmp/webapps/
      flat: yes

- name: Deploy artifact in docker
  hosts: production
  become: yes

  tasks:
  - name: Build container
    docker_container:
      name: production
      image: tomcat:jre8-alpine
      ports:
        - "8080:8080"

  - name: Copy artifact from localhost
    copy:
      src: /tmp/webapps/hello-1.0.war
      dest: /tmp/webapps
      mode: 0644

  - name: Copy artifact to container
    shell: "docker cp /tmp/webapps/hello-1.0.war production:/usr/local/tomcat/webapps/"

