---
- name: Package artifact in Docker
  hosts: build
  become: yes

  tasks:
  - name: Install pip
    apt:
      name: python3-pip
      update_cache: yes

  - name: Install Docker
    pip:
      name: docker

  - name: Copy container from localhost
    copy:
      src: /home/user/ansible-docker/docker-build/Dockerfile
      dest: /tmp/docker/
      mode: 0644

  - name: Build container
    docker_image:
      path: /tmp/docker/
      name: build

  - name: Start container
    docker_container:
      name: build
      image: build

  - name: Copy artifact from container
    shell: "mkdir /tmp/webapps; docker cp build:/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/webapps"

  - name: Fetch artifact from remote host
    fetch:
      src: /tmp/webapps/hello-1.0.war
      dest: /tmp/webapps/
      flat: yes
