---
- name: Package artifact
  hosts: build
  become: yes

  tasks:
  - name: Install Maven
    apt:
      name: maven
      update_cache: yes

  - name: Clone repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse-sample-java-war-hello/

  - name: Package webapp
    shell: cd /tmp/boxfuse-sample-java-war-hello/; mvn package

  - name: Copy artifact
    command: "{{ item }}"
    with_items:
      - mkdir /tmp/webapps
      - cp /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/webapps
    args:
      creates: /tmp/webapps/hello-1.0.war

  - name: Fetch artifact from remote host
    fetch:
      src: /tmp/webapps/hello-1.0.war
      dest: /tmp/
      flat: yes

- name: Deploy
  hosts: production
  become: yes

  tasks:
  - name: Install Tomcat
    apt:
      name: tomcat9
      update_cache: yes

  - name: Start Tomcat, if not running
    service:
      name: tomcat9
      state: started

  - name: Copy artifact from localhost
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
      mode: 0644
---