---
- name: Package artifact
  hosts: build
  become: yes

  tasks:
  - name: Install Maven
    apt:
      name: maven
      update_cache: yes

  - name: Clone repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse-sample-java-war-hello/

  - name: Package webapp
    shell: cd /tmp/boxfuse-sample-java-war-hello/; mvn package; mkdir /tmp/webapps; cp /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/webapps

  - name: Fetch artifact
    fetch:
      src: /tmp/webapps/hello-1.0.war
      dest: /tmp/